### PR TITLE
Dont return SMTP password

### PR DESCRIPTION
**Pull request by Meatballs1**
Campaign pages returns the SMTP password in cleartext in the form.

### CODE REVIEW

**Comment by Meatballs1** [comment]
Dunno if this is right approach, means you cant set an SMTP password back to blank...

**Comment by zeknox** [comment]
Hey @Meatballs1, just want to apologize up front for any delays here, gonna be out of town this weekend so wont be able to look at all the great additions you're mustering up.  Keep em coming!

**Comment by Meatballs1** [comment]
No worries, I understand the time restraints!

**Comment by Meatballs1** [comment]
Cheers :)

**Pull request merged**
