### PR TITLE
Add System Logfiles

### PR DESCRIPTION
**Pull request by Meatballs1**
First attempt, have some CSS issues with the LI numbering...

Should probably add a LICENSE for app/assets/stylesheets/system_logs.scss  as its mostly taken from gitlabhq project :)

### CODE REVIEW

**Comment by zeknox** [comment]
Looks like `Gemfile` is missing the package `file-tail`

Ended up throwing errors when starting sidekiq without it:
<pre>
# sidekiq
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.1.7/lib/active_support/dependencies.rb:247:in `require': No such file to load -- file/tail (LoadError)
</pre>

**Comment by zeknox** [comment]
I must be doing something wrong with `file-tail`, throwing errors when accessing the new system_logs view:

screen shot 2015-07-16 at 7 45 03 pm

**Comment by Meatballs1** [comment]
Ah yes I dont think I updated the Gemfile. I will correct, have you bundle installed etc?

**Comment by zeknox** [comment]
Yeah, I added it to Gemfile and bundled, but still ended up with this crash shown above.

**Comment by Meatballs1** [comment]
Rebased to: https://github.com/pentestgeek/phishing-frenzy/pull/198

**Pull request closed without merging**
