### PR TITLE
System Logs (Rebased)

### PR DESCRIPTION
**Pull request by Meatballs1**
I rebased this off the current master - so pushed to new branch. Hopefully gem changes work ok

image

Have included some specs as well.

```
bundle exec rspec spec/views/system_logs/show.html.erb_spec.rb
bundle exec rspec spec/controllers/system_logs_controller_spec.rb
bundle exec rspec spec/helpers/system_logs_helper_spec.rb
```

There is currently 68 failing specs in master (and same on my branch) at the moment, so I dont think the spec helper changes have done any harm!

### CODE REVIEW

**Comment by zeknox** [comment]
One observation here, it seems like the development log and sidekiq log is showing the first 2000 lines, when the message on systems_logs view states:

 `To prevent performance issues admin logs output the last 2000 lines`

**Comment by Meatballs1** [comment]
Is your logfile > 2000 ?

**Comment by zeknox** [comment]
It seems a lot of my tests don't like the refactor you performed to the `login_admin`.

<pre>
root@bt:/var/www/phishing-frenzy# rspec
..............FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.......FFFFFFFFFFFFFFFFFFFFFFFFF....

Failures:

  1) Admins GET /admins/list requests admin list page to view admins
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `env' for nil:NilClass
     # ./spec/support/controller_macros.rb:4:in `block in login_admin'

</pre>

Any ideas why this is?

**Comment by Meatballs1** [comment]
Ah they are integration tests. They dont have a @request object by the looks of it. Seems the way to accomodate them might be to follow:

https://github.com/plataformatec/devise/wiki/How-To:-Test-with-Capybara

**Comment by zeknox** [comment]
Yes these are integration / request specs.  I leverage capybara to make the actual HTTP request when testing and clicking based on DOM selection. e.g.

```ruby
    it "approve an existing admins account" do
      create(:admin, :unapproved)
      visit list_admin_index_path
      first(:link, "Approve").click
      expect(page).to have_http_status(200)
    end
```

**Comment by zeknox** [comment]
Once we get to the bottom of why these tests are failing I'm comfortable merging this into master.

**Comment by Meatballs1** [comment]
So I had to add a second method to login as an admin which would work in the scope of just a controller spec, rather than a full integration test.

Not sure if ControllerMacros should be split into RequestMacros and ControllerMacros?

**Pull request merged**
