### PR TITLE
Add Reply To option in Campaign Settings

### PR DESCRIPTION
**Pull request by Meatballs1**
This adds reply_to field to the Campaign Email Settings:

image

I have only tested using a local debugging SMTP server:

```
---------- MESSAGE FOLLOWS ----------
Date: Tue, 14 Jul 2015 21:06:12 +0100
From: TEST <test@pf.local>
Reply-To: reply@pf.local
To: ben@test.com
Message-ID: <55a56bb41ee4e_49573fc8dc0e37a8747e0@ben-dev.mail>
Subject: Testte
Mime-Version: 1.0
Content-Type: multipart/related;
 boundary="--==_mimepart_55a56bb41e1eb_49573fc8dc0e37a8746fb";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
X-Peer: 127.0.0.1


----==_mimepart_55a56bb41e1eb_49573fc8dc0e37a8746fb
```

Also think I have picked out a couple of bugs in the mailer:

* Track wasn't being used - all the URLs were being created with tracking UIDs regardless of this setting
* Previews weren't getting the Display settings of From

I have reduced code duplication in places, which should help prevent some of these issues in the future.

### CODE REVIEW

**Comment by zeknox** [comment]
Nifty! excited to try this out and expand its capabilities... I've entertained having PF receive emails for a long time now using something like the mailman Gem. This addition would just help pave the way...

**Comment by Meatballs1** [comment]
I just spun up iRedMail to handle incoming mail, but having the option to receive via PF would also be useful. 

Key features:

* Receive replies all to a single inbox
* Ability to set the From and Display From fields when replying
* Attaching another attachment - some of the best replies are - 'The macro isn't working help!', 'The executable was blocked help!' ;)

**Comment by zeknox** [comment]
Another option to quickly receive emails with minimal deployment is to leverage Sengrid's hook capabilities. This obviously requires you send your mail through Sendgrid but then they have the ability to hook any messages replied to.

**Comment by Meatballs1** [comment]
Yes, but requires spinning up something to handle the SendGrid hook API. I've only just managed to get whitelabelling working.

**Comment by Meatballs1** [comment]
I haven't captured background mails here... Will fix up.

**Comment by Meatballs1** [comment]
Ah the if/else statement was for ACTIVE/PREVIEW not for ACTIVE/DELAYED as I originally understood. Should be ok for Background mails already, but have fixed Preview :)

**Pull request merged**
