### PR TITLE
Use SMTP Domain for message ID

### LINKED ISSUE #209: Mail message ID contains system hostname
Looks like ruby's Mail library creates a random identifier and appends @SYSTEM_NAME.mail

Would be good to anonymize this :)

### PR DESCRIPTION
**Pull request by Meatballs1**
Fixes #209 
### Before

```
sudo python -m smtpd -n -c DebuggingServer localhost:1025 |grep ben-dev
Message-ID: <55ad48f784f7b_134c3ad561c1016c8@ben-dev.mail>
  <img src="cid:55ad4e86132d5_134c3ad561c103015@ben-dev.mail" />
Content-ID: <55ad4e86132d5_134c3ad561c103015@ben-dev.mail>
```
### After

```
Message-ID: <55ad5597a5502_134c3fc7b60bc814107264@test.com>
  <img src="cid:55ad5597a5502_134c3fc7b60bc814107264@test.com" />
Content-ID: <55ad5597a5502_134c3fc7b60bc814107264@test.com>
```
## Verify
- [ ] Inline images still display correctly!

### CODE REVIEW

**Comment by Meatballs1** [comment]
I have also wired up the smtp domain setting so we will EHLO/HELO with that:

image

**Comment by Meatballs1** [comment]
Fix conflicts

**Comment by zeknox** [comment]
Why do I feel like the mailer is not honoring the smtp_domain within the mailer_id.  Just did some testing locally here and this was the message_id:
<pre>Message-ID: <562f11d8c7c6b_28f51c486b866150@kali.mail></pre>

kali is my hostname and the smtp_domain was phishingfrenzy.local

**Comment by Meatballs1** [comment]
It should be, it appeared fine in my pcaps?

Just wondering do you need to restart sidekiq or something? I'm not sure how/when it picks up changes to the code base.

**Pull request merged**
